<a href="https://colab.research.google.com/github/ramasamybenazir-deep/Numpy-and-panda-assignment/blob/main/Numpy_and_panda_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
print("NumPy and Pandas are ready to use!")

NumPy and Pandas are ready to use!


In [4]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])


In [5]:

print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [6]:
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [7]:
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")

print(temperatures_f)

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [8]:
print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))

Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [9]:
first_three_days = temperatures_w1[:3]

print("First Three Days:")
print(first_three_days)

First Three Days:
[22.5 25.3 20.8]


In [10]:

weekend = temperatures_w1[-2:]

print("Weekend Temperatures:")
print(weekend)

Weekend Temperatures:
[24.8 21.9]


In [11]:
middle_three_days = temperatures_w1[2:5]

print("Middle Three Days:")
print(middle_three_days)

Middle Three Days:
[20.8 23.4 26.1]


In [12]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("Temperature Array:")
print(temperatures)

Temperature Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [13]:
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14


In [14]:
week1 = temperatures[0]

print("Week 1:")
print(week1)

Week 1:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [15]:
week2 = temperatures[1]

print("Week 2:")
print(week2)

Week 2:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [16]:
week1_weekend = temperatures[0, -2:]

print("Week 1 Weekend:")
print(week1_weekend)

Week 1 Weekend:
[24.8 21.9]


In [ ]:
week2_weekend = temperatures[1, -2:]

print("Week 2 Weekend:")
print(week2_weekend)

In [17]:
weekends = temperatures[:, -2:]

print("Weekends for Both Weeks:")
print(weekends)

Weekends for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]


In [18]:
#  create Pandas Series
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("Marks Series:")
print(marks)

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [19]:
first_rank = marks.iloc[0]

print("Mark of 1st Rank:", first_rank)

Mark of 1st Rank: 95


In [20]:
top_three = marks.loc[['Rank1', 'Rank2', 'Rank3']]

print("Top 3 Ranks:")
print(top_three)

Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [21]:
third_rank = marks.iloc[2]

print("Mark of 3rd Rank:", third_rank)
above_90 = marks[marks > 90]

print("Marks Greater Than 90:")
print(above_90)

Mark of 3rd Rank: 89
Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


In [22]:
marks.loc['Rank1'] = 100

print("After modifying Rank 1:")
print(marks)

After modifying Rank 1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [23]:
marks = marks.drop('Rank5')

print("After removing Rank 5:")
print(marks)

After removing Rank 5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [24]:
cgpa = marks / 10

print("CGPA:")
print(cgpa)

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [25]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [27]:
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [28]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [29]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [30]:
print("Shape:", transactions.shape)

Shape: (10, 4)


In [31]:
print("Column Names:")
print(transactions.columns)

Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [32]:
print("Data Types:")
print(transactions.dtypes)

Data Types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [33]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [34]:
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [35]:
print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [36]:
filtered_data = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_data)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [37]:
category_counts = transactions['ProductCategory'].value_counts()

print(category_counts)

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [38]:
unique_regions = transactions['Region'].unique()

print("Unique Regions:")
print(unique_regions)

Unique Regions:
['North' 'South' 'East' 'West']


In [39]:
mean_amount_region = transactions.groupby('Region')['Amount'].mean()

print("Mean Amount by Region:")
print(mean_amount_region)

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [40]:
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [41]:
transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [42]:
transactions = transactions[
    transactions['TransactionID'] != 109
]

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [43]:
transactions = transactions.drop('Discount', axis=1)

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
